### ISSUE TITLE
Speeding up ZMQ things

### ISSUE THREAD

**Issue by roshambo919** [avstack-lab/demo-platform#7]
Looking into:
- `copy=False` on data transfers
- Multiple workers for data-intensive threads
- Using inter-process communications that are faster (see http://api.zeromq.org/2-1:zmq-ipc)

**Comment by natezelter1** [comment]
Resolved. Used a mix of JPEG compression and image interpolation to reduce transmission packet size by >32x. copy=False is a good thing, and that's what has been used so far. Inter-process comms looks very promising actually, but it placed on backlog for now.

**Comment by roshambo919** [comment]
Nice! 32x! If it is resolved, let's put in a pull request for your feature branch tomorrow so we can get it into main.
